"""Normalise ISE-DSC01 into the common schema.

ISE-DSC01 is the corpus that makes the chunk-aware contribution testable: its contexts run to
21–73 sentences, so attention has somewhere to be distributed, and most rows name the exact
sentence that settles the claim. Section 7 of docs/DATA.md specifies the mapping.

Only ``isedsc01_train.json`` is read. The two test files carry no ``verdict``, so they have no
label and cannot be used.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from vihallulens.data.schema import (
    context_id,
    encode_meta,
    finalise,
    find_evidence,
    sample_id,
)

DATASET = "isedsc01"
SPLIT = "train"
SOURCE_FILE = "isedsc01_train.json"

# Section 3 of docs/DATA.md. NEI maps to extrinsic by approximation, not by equivalence: NEI
# means "the context does not settle this", while extrinsic hallucination means "this brings in
# something the context never said". The two overlap heavily but are not the same, which is why
# task T13 audits 100 of them by hand and the report has to state the caveat.
VERDICT_TO_LABEL = {"SUPPORTED": "no", "REFUTED": "intrinsic", "NEI": "extrinsic"}

# Section 4 of docs/DATA.md, verified at task T08B.
EXPECTED_ROWS = 36369
EXPECTED_LABELS = {"no": 12786, "intrinsic": 11000, "extrinsic": 12583}


def normalize_isedsc01(raw_dir: Path) -> pd.DataFrame:
    """Read the corpus, check it against the documented counts, and return it.

    Split from :func:`read_isedsc01` so the reading can be exercised on a handful of rows.
    The size check is what makes a changed release fail loudly, and it is also what makes a
    two-row fixture impossible to run through, so the two jobs live in separate functions.
    """
    frame = read_isedsc01(raw_dir)
    check_expected(frame)
    return frame


def read_isedsc01(raw_dir: Path) -> pd.DataFrame:
    """Read ``isedsc01_train.json`` and return it in the common schema."""
    source = Path(raw_dir) / SOURCE_FILE
    if not source.is_file():
        raise FileNotFoundError(f"không thấy {source}")

    with source.open(encoding="utf-8") as handle:
        raw = json.load(handle)
    if not isinstance(raw, dict):
        raise ValueError(
            f"{SOURCE_FILE} phải là một dict với khóa là số thứ tự dạng chuỗi, "
            f"đang là {type(raw).__name__}"
        )

    records = []
    for index, (key, record) in enumerate(raw.items()):
        verdict = str(record.get("verdict", ""))
        if verdict not in VERDICT_TO_LABEL:
            raise ValueError(f"bản ghi {key} có verdict lạ: {verdict!r}")

        context = str(record.get("context", ""))
        # NEI rows carry JSON null here rather than an empty string, so the fallback matters.
        evidence = str(record.get("evidence") or "")
        start, end = find_evidence(context, evidence)
        records.append(
            {
                "sample_id": sample_id(DATASET, SPLIT, index),
                "dataset": DATASET,
                "split": SPLIT,
                "context": context,
                "context_id": context_id(context),
                # A fact-checking corpus: there is no question, only a claim to judge.
                "question": "",
                "response": str(record.get("claim", "")),
                "label": VERDICT_TO_LABEL[verdict],
                "label_original": verdict,
                # Keep the evidence only when it was actually located. Storing text whose
                # offsets say "not found" would let a later experiment use one field while
                # trusting the other.
                "evidence": evidence if start >= 0 else "",
                "evidence_start": start,
                "evidence_end": end,
                # Claims were written by annotators, not generated by a model.
                "response_is_generated": False,
                "meta": encode_meta(
                    {
                        "source_id": str(key),
                        "domain": str(record.get("domain", "")),
                        # Distinguishes "no evidence in this corpus for this row" from
                        # "evidence exists but could not be located in the context".
                        "evidence_given": bool(evidence.strip()),
                    }
                ),
            }
        )

    return finalise(pd.DataFrame.from_records(records))


def check_expected(frame: pd.DataFrame) -> None:
    """Compare against the counts verified at task T08B and raise on any difference."""
    if len(frame) != EXPECTED_ROWS:
        raise ValueError(
            f"ISE-DSC01 có {len(frame)} dòng, mục 4 docs/DATA.md ghi {EXPECTED_ROWS}"
        )
    counts = frame["label"].value_counts().to_dict()
    if counts != EXPECTED_LABELS:
        raise ValueError(
            f"phân bố nhãn {counts} khác bảng mục 4 docs/DATA.md {EXPECTED_LABELS}"
        )
