"""Normalise ViHallu into the common schema.

ViHallu is the corpus the whole thesis is framed around, and the only one of the four whose
``response`` was actually generated by an LLM rather than written by an annotator as a claim.
Section 7 of docs/DATA.md specifies the mapping; this module implements it.

Only ``vihallu_train.csv`` is read. ``vihallu_test_public.csv`` exists but its label column is
empty for every row, so it cannot be used for anything and is not touched.
"""

from __future__ import annotations

import unicodedata
from pathlib import Path

import pandas as pd

from vihallulens.data.schema import (
    NO_OFFSET,
    context_id,
    encode_meta,
    finalise,
    sample_id,
)

DATASET = "vihallu"
SPLIT = "train"
SOURCE_FILE = "vihallu_train.csv"

# Section 4 of docs/DATA.md, verified at task T08B. Checked after normalising so that a
# corrupted download or a changed release is caught here rather than in an experiment.
EXPECTED_ROWS = 7000
EXPECTED_LABELS = {"no": 2245, "intrinsic": 2448, "extrinsic": 2307}

PROMPT_TYPE_NOISY = "noisy"
PROMPT_TYPE_UNKNOWN = "unknown"


def is_diacritic_letter(char: str) -> bool:
    """Is this a Latin letter carrying a Vietnamese diacritic?

    Derived from Unicode rather than from a hand-written list, as section 7 of docs/DATA.md
    requires. A letter qualifies when its canonical decomposition splits into an ASCII letter
    plus one or more combining marks — which covers every toned and hatted vowel, from ``á``
    through ``ệ`` to ``ự`` — and ``đ`` is added by name because it carries a stroke rather
    than a combining mark and so does not decompose, yet vanishes just the same when the text
    is stripped of diacritics.
    """
    if char in "đĐ":
        return True
    decomposed = unicodedata.normalize("NFD", char)
    return len(decomposed) > 1 and decomposed[0].isascii() and decomposed[0].isalpha()


def has_diacritics(text: str) -> bool:
    """Does the text contain any Vietnamese diacritic at all?"""
    return any(is_diacritic_letter(char) for char in unicodedata.normalize("NFC", text))


def infer_prompt_type(prompt: str, context: str) -> str:
    """Guess which of the three ViHallu prompt families this prompt belongs to.

    The corpus ships no column saying so, and section 7 of docs/DATA.md allows exactly one
    reliable inference: a prompt with no diacritics beside a context that has them was
    stripped on purpose, so it is ``noisy``.

    The comparison against the context is what makes it safe. Judging the prompt alone would
    label a short prompt made only of names and numbers as noisy, when in fact it never had a
    diacritic to lose.

    ``factual`` and ``adversarial`` are not separable by any simple rule, so both come back as
    ``unknown``. Guessing between them would put invented labels into a column that task T35
    later slices results by.
    """
    if not has_diacritics(prompt) and has_diacritics(context):
        return PROMPT_TYPE_NOISY
    return PROMPT_TYPE_UNKNOWN


def normalize_vihallu(raw_dir: Path) -> pd.DataFrame:
    """Read ``vihallu_train.csv`` and return it in the common schema."""
    source = Path(raw_dir) / SOURCE_FILE
    if not source.is_file():
        raise FileNotFoundError(f"không thấy {source}")

    raw = pd.read_csv(source, dtype=str, keep_default_na=False)
    expected_columns = {"id", "context", "prompt", "response", "label"}
    missing = expected_columns - set(raw.columns)
    if missing:
        raise ValueError(f"{SOURCE_FILE} thiếu cột: {', '.join(sorted(missing))}")

    records = []
    for index, row in enumerate(raw.itertuples(index=False)):
        context, prompt = str(row.context), str(row.prompt)
        prompt_type = infer_prompt_type(prompt, context)
        records.append(
            {
                "sample_id": sample_id(DATASET, SPLIT, index),
                "dataset": DATASET,
                "split": SPLIT,
                "context": context,
                "context_id": context_id(context),
                # ViHallu's "prompt" is the question put to the model that wrote the response.
                "question": prompt,
                "response": str(row.response),
                # ViHallu already uses the three target labels, so no mapping is needed; the
                # original is still kept, so every corpus can be traced back the same way.
                "label": str(row.label),
                "label_original": str(row.label),
                # No evidence column exists in this corpus.
                "evidence": "",
                "evidence_start": NO_OFFSET,
                "evidence_end": NO_OFFSET,
                # The one corpus where the text being judged was written by an LLM.
                "response_is_generated": True,
                "meta": encode_meta(
                    {
                        "source_id": str(row.id),
                        "prompt_type": prompt_type,
                        "prompt_has_diacritics": prompt_type != PROMPT_TYPE_NOISY,
                    }
                ),
            }
        )

    frame = finalise(pd.DataFrame.from_records(records))
    check_expected(frame)
    return frame


def check_expected(frame: pd.DataFrame) -> None:
    """Compare against the counts verified at task T08B and raise on any difference.

    Section 4 of docs/DATA.md says to stop and report rather than carry on when the numbers
    move: a shifted label distribution means a different release of the corpus, and results
    from it are not comparable with anything measured before.
    """
    if len(frame) != EXPECTED_ROWS:
        raise ValueError(
            f"ViHallu có {len(frame)} dòng, mục 4 docs/DATA.md ghi {EXPECTED_ROWS}"
        )
    counts = frame["label"].value_counts().to_dict()
    if counts != EXPECTED_LABELS:
        raise ValueError(
            f"phân bố nhãn {counts} khác bảng mục 4 docs/DATA.md {EXPECTED_LABELS}"
        )
