"""A minimal RAG system around the detector (task T40): retrieve, answer, score.

Twenty short Vietnamese documents, BM25 retrieval, and the answer generated by **the same
reading model the detector already holds** — Qwen2.5-7B is loaded once for scoring, and asking
it to also write the answer costs no second model and no second GPU. This is also the setting
the thesis's cost argument describes (Bảng 8): the reading pass a RAG system pays for anyway is
the pass the detector reads its features from.

The generation prompt is the locked template of CLAUDE.md §8 with ``add_generation_prompt``
instead of a filled assistant turn, so the answer is produced from exactly the string the
detector will later score. Greedy decoding, so the demo is reproducible.

Deliberately small. The point is not the retriever — ``docs/DATA.md`` §8 already chose BM25 for
the same reason at E08 — but that a question typed into the page comes back with an answer
*and* a risk score, end to end, with the context tinted by where the model looked.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

from vihallulens.data.retrieval import EvidenceIndex, Hit
from vihallulens.extract.prompt import SYSTEM_PROMPT, build_user_turn

DEMO_CORPUS = Path(__file__).parent / "demo_corpus.jsonl"
DEFAULT_TOP_K = 3
MAX_NEW_TOKENS = 160


def load_corpus(path: Path | str = DEMO_CORPUS) -> pd.DataFrame:
    rows = [json.loads(line) for line in Path(path).read_text(encoding="utf-8").splitlines()
            if line.strip()]
    if not rows:
        raise ValueError(f"kho demo rỗng: {path}")
    return pd.DataFrame(rows)


def corpus_documents(corpus: pd.DataFrame) -> list[dict]:
    return [{"id": r.evidence_id, "title": r.title, "text": r.text}
            for r in corpus.itertuples(index=False)]


def join_context(hits: list[Hit]) -> str:
    """One context string from the retrieved documents, best first, blank line between."""
    return "\n\n".join(hit.text for hit in hits)


def generate_answer(extractor, context: str, question: str,
                    max_new_tokens: int = MAX_NEW_TOKENS) -> str:
    """Ask the loaded reading model to answer from the context, with the locked template."""
    import torch

    tokenizer, model = extractor.tokenizer, extractor.model
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_user_turn(context, question)},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        output = model.generate(
            **inputs, max_new_tokens=max_new_tokens, do_sample=False,
            pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
        )
    new_tokens = output[0, inputs["input_ids"].shape[1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


@dataclass
class RagAnswer:
    question: str
    retrieved: list[dict]
    context: str
    answer: str
    score: dict
    elapsed_ms: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {"question": self.question, "retrieved": self.retrieved, "context": self.context,
                "answer": self.answer, "score": self.score, "elapsed_ms": self.elapsed_ms}


class DemoRAG:
    """Retrieve → answer → score, over the bundled demo corpus.

    ``generator`` is a callable ``(extractor, context, question) -> str``; it defaults to
    :func:`generate_answer` and exists so the tests can run the whole path without a model.
    """

    def __init__(self, detector, corpus: pd.DataFrame | None = None, top_k: int = DEFAULT_TOP_K,
                 generator=None):
        self.detector = detector
        self.corpus = corpus if corpus is not None else load_corpus()
        self.index = EvidenceIndex(self.corpus)
        self.top_k = top_k
        self.generator = generator or generate_answer

    def retrieve(self, question: str, top_k: int | None = None) -> list[Hit]:
        return self.index.search(question, k=top_k or self.top_k)

    def ask(self, question: str, top_k: int | None = None) -> RagAnswer:
        timings = {}
        t = time.perf_counter()
        hits = self.retrieve(question, top_k)
        timings["retrieve"] = (time.perf_counter() - t) * 1000
        if not hits:
            raise ValueError("không truy xuất được tài liệu nào cho câu hỏi này")
        context = join_context(hits)

        t = time.perf_counter()
        answer = self.generator(self.detector.extractor, context, question)
        timings["generate"] = (time.perf_counter() - t) * 1000
        if not answer:
            raise ValueError("mô hình không sinh được câu trả lời")

        t = time.perf_counter()
        result = self.detector.score(context, question, answer)
        timings["score"] = (time.perf_counter() - t) * 1000

        return RagAnswer(
            question=question,
            retrieved=[{"id": h.evidence_id, "title": h.title, "score": round(h.score, 3),
                        "rank": h.rank} for h in hits],
            context=context,
            answer=answer,
            score=result.to_dict(),
            elapsed_ms=timings,
        )

    def documents(self) -> list[dict]:
        return corpus_documents(self.corpus)
